### ISSUE TITLE
How does databases are integrated?

### ISSUE THREAD

**Issue by Pavan637** [bio4j/bio4j#89]
Are those databases integrated through cypher only.
Can in know in which format these databases are imported in bio4j

**Comment by pablopareja** [comment]
Hi Pavan637,

The different data sources can currently be imported in either Neo4j or Titan graph databases. 
Both of them support [Blueprints](https://github.com/tinkerpop/blueprints/wiki) which would be the common API for both of them. _(You could therefore use [Gremlin](https://github.com/tinkerpop/gremlin/wiki) query language with any of the two)_ 

Of course you could also use our Java API with any of the two implementations as well.

Cheers,

Pablo
