### ISSUE TITLE
where and how are docs published?

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/bio4j#91]
Hey @laughedelic how this works now?

**Comment by laughedelic** [comment]
Which docs?
- API is at http://bio4j.com/bio4j/docs/api/0.12.0-RC1/ for example
- literator docs are in https://github.com/bio4j/bio4j/tree/master/docs/src/

**Comment by eparejatobes** [comment]
fine that's what I needed to know thanks!

**Comment by eparejatobes** [comment]
oh and another thing; is it somehow possible to publish the literator docs as htmls somewhere?

**Comment by laughedelic** [comment]
well, literator makes only markdown files. if you want to generate htmls from them, you need some other tool.

**Comment by eparejatobes** [comment]
OK fine. Closing
