### ISSUE TITLE
Is there an open platform for users? 

### ISSUE THREAD

**Issue by elephantsuperjuan** [bio4j/bio4j#99]
As bio4j blog says, bio4j has been integrated in a graph DB with easy AWS deployment. But I can't find an entrance to the AWS deployment. Is it already open for users?

**Comment by pablopareja** [comment]
Hi @elephantsuperjuan 
Yeah, it's totally open for users indeed, did you already have a look [here](https://github.com/bio4j/bio4j-titan/blob/master/docs/Bio4jAWSReleases.md) ?

**Comment by elephantsuperjuan** [comment]
Oh, Thank you.

**Comment by elephantsuperjuan** [comment]
I can't access the s3://eu-west-1.raw.bio4j.com/ directly. Did I need an account of AWS? And It is not easy to get an account without a credit card.

**Comment by elephantsuperjuan** [comment]
I have asked the AWS's customer service staff. And they say this web may not have make it open. So I can't access it. So can you make it public? In this way, users don't need an AWS account. Actually, I just wonder how Bio4j works. Maybe I can do something on it since it's a wonderful work. Thanks a lot.

**Comment by eparejatobes** [comment]
hey @elephantsuperjuan let's see if we can help you here. We just improved (I hope, bio4j/bio4j-titan#66 ) the docs on using the bio4j Titan distribution on AWS:

- [bio4j/bio4j-titan Pre-built bio4j releases in AWS](https://github.com/bio4j/bio4j-titan/blob/master/docs/Bio4jAWSReleases.md)

if there's something missing there we are happy to expand on it. Answering to what you wrote here, yes you do need an AWS account if you want to use the pre-imported Bio4j Titan distribution. There also gitter: https://gitter.im/bio4j/bio4j if you need help.
